### ISSUE TITLE
请问支持甲骨文ARM吗？

### ISSUE THREAD

**Issue by hkbbdx** [haozi-team/panel#1]
请问支持甲骨文ARM吗？

如可以，我就重装来试试看

**Comment by DevHaoZi** [comment]
不支持，等目前版本趋于完善稳定后才会考虑兼容别的系统/架构

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
> 不支持，等目前版本趋于完善稳定后才会考虑兼容别的系统/架构

希望早日支持大便和Ubuntu

**Comment by DevHaoZi** [comment]
Hi @hkbbdx 👋

我们认为您的反馈非常有价值！如果有兴趣欢迎前往 极狐GitLab 仓库提交 PR，请包含相应的测试用例、文档等，并确保 CI 通过，感谢和期待您的贡献！
We think your feedback is very valuable! If you are interested, please submit a PR to JiHu GitLab repository, please include test cases, documentation, etc., and ensure that the CI is passed, thank you and look forward to your contribution!

**Comment by DevHaoZi** [comment]
> > 不支持，等目前版本趋于完善稳定后才会考虑兼容别的系统/架构
> 
> 希望早日支持大便和Ubuntu

已经支持Debian安装

**Comment by DevHaoZi** [comment]
> 请问支持甲骨文ARM吗？
> 
> 如可以，我就重装来试试看

2.0做了Arm支持，但是暂时没有机器测试，你可以自行测试一下。
