### ISSUE TITLE
✨ [Feature] 证书管理功能

### ISSUE THREAD

**Issue by devhaozi** [haozi-team/panel#38]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

添加V1面板中的免费证书签发到V2面板。

### 工作流程 (WorkFlow)

None

**Comment by DevHaoZi** [comment]
关联`github.com/go-acme/lego`，看起来非常有趣。
