### ISSUE TITLE
✨ [Feature] 希望可以加入php5.3和5.6版本

### ISSUE THREAD

**Issue by xu5343** [haozi-team/panel#59]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

一些程序php5.4和php5,6版本才能跑起来，7.4版本起步太高了

### 工作流程 (WorkFlow)

1. 新建文件 ....
2. 添加函数 ....
3. ...

### 还有别的吗 (Anything Else)

没有了

**Comment by devhaozi** [comment]
这个没有计划，我们一般不会考虑添加已经停止支持的软件，一来会影响安全性，二来会增加额外的维护成本。
实在有需求可以自行修改安装脚本安装，但是无法在面板上管理。
