### ISSUE TITLE
This program can only be run on AMD64 processors with v2 microarchitecture support.

### ISSUE THREAD

**Issue by dxdbl** [haozi-team/panel#65]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在升级之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

12

### 耗子面板版本 (HaoZi Panel Version)

最新版

### 描述问题 (Describe The Problem)

Rule added (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall reloaded
Created symlink /etc/systemd/system/multi-user.target.wants/panel.service → /etc/systemd/system/panel.service.
+----------------------------------------------------
| 耗子 Linux 面板安装脚本
+----------------------------------------------------
| Copyright © 2022-2024 耗子科技 All rights reserved.
+----------------------------------------------------
面板安装成功！
+----------------------------------------------------
This program can only be run on AMD64 processors with v2 microarchitecture support.
This program can only be run on AMD64 processors with v2 microarchitecture support.

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 预期行为 (Expected Behavior)

正常安装

### 相关日志 (Related Logs)

Creating config file /etc/ufw/after6.rules with new version
Created symlink /etc/systemd/system/multi-user.target.wants/ufw.service → /lib/systemd/system/ufw.service.
Processing triggers for rsyslog (8.2302.0-1) ...
Processing triggers for man-db (2.11.2-2) ...
Command may disrupt existing ssh connections. Proceed with operation (y|n)? Firewall is active and enabled on system startup
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Rule added
Rule added (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall reloaded
Created symlink /etc/systemd/system/multi-user.target.wants/panel.service → /etc/systemd/system/panel.service.
+----------------------------------------------------
| 耗子 Linux 面板安装脚本
+----------------------------------------------------
| Copyright © 2022-2024 耗子科技 All rights reserved.
+----------------------------------------------------
面板安装成功！
+----------------------------------------------------
This program can only be run on AMD64 processors with v2 microarchitecture support.
This program can only be run on AMD64 processors with v2 microarchitecture support.

### 还有别的吗 (Anything Else)

服务器CPU是 AMD Ryzen 9 7950X3D 16-Core "Raphael" (Zen 4)

**Comment by devhaozi** [comment]
![image](https://github.com/haozi-team/panel/assets/115467771/451840fc-3ab7-4880-9695-51fe17fa9687)

感觉得问一下商家，为什么没开启 v2 下的指令集。

**Comment by dxdbl** [comment]
OK

耗子 ***@***.***> 于2024年1月8日周一 02:47写道：
